#!/bin/bash

set -e

HOMETIME="18:00:00"
USB_DRIVE_NAME="ginkgo"

HOURS="$1"
PRIVATE_KEY="/Volumes/${USB_DRIVE_NAME}/id_rsa"

main() {
  ensure_ssh_agent_is_running
  delete_all_ssh_identities
  add_private_key
}

ensure_ssh_agent_is_running() {
  eval "$(ssh-agent -s)"
}

delete_all_ssh_identities() {
  ssh-add -D
}

add_private_key() {
  if [ -z "$HOURS" ]
  then
    add_private_key_until_hometime
  else
    add_private_key_for_hours
  fi
}

add_private_key_until_hometime() {
  local now="$(date +%s)"
  local until="$( date -j -f "%T" $HOMETIME +%s )"
  local seconds_remaining="$( expr $until - $now )"

  if [ "$seconds_remaining" -lt 1 ]
  then
    echo "$HOMETIME is already history!"
    exit 1
  else
    echo "Adding Josh's private key until $HOMETIME..."
    ssh-add -t "$seconds_remaining" "$PRIVATE_KEY"
  fi
}

add_private_key_for_hours() {
  echo "Adding Josh's private key for $HOURS hours..."
  ssh-add -t "${HOURS}h" "$PRIVATE_KEY"
}

main
