#!/bin/bash

# Bash
cp ~/.bash_profile bash/bash_profile
cp ~/bin/loadkey bash/bin/loadkey

# Powerline shell
cp ~/.powerline-shell/config.py powerline-shell/
cp ~/.powerline-shell/powerline-shell.py powerline-shell/

# Fish
cp ~/.config/fish/config.fish fish/
cp ~/.config/fish/fishd.* fish/
cp ~/.config/fish/functions/*.fish fish/functions/

# Git
cp ~/.gitconfig git/gitconfig
cp ~/.gitignore git/gitignore

# Brew
brew list > brew/brew-list.txt
brew cask list > brew/brew-cask-list.txt

# rbenv
cp ~/.rbenv/default-gems rbenv/

# Rubygems
cp ~/.gemrc ruby/gemrc

# Vim
cp ~/.vimrc.local vim/vimrc.local

# Sublime Text 2
cp ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/*.sublime-settings sublime2/
cp ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Default\ \(OSX\).sublime-keymap sublime2/

# Sublime Text 3
cp ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/*.sublime-settings sublime3/
cp ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Default\ \(OSX\).sublime-keymap sublime3/

# Atom
cp ~/.atom/config.cson atom/
cp ~/.atom/init.coffee atom/
cp ~/.atom/keymap.cson atom/
cp ~/.atom/snippets.cson atom/
cp ~/.atom/styles.less atom/
ls -d ~/.atom/packages/*/ | cut -d'/' -f6 > atom/atom-packages.txt
