#!/usr/bin/env fish

function main
    stow_config
    configure_homebrew
    update_homebrew
    generate_homebrew_bundle
    install_homebrew_bundle
    run_install_scripts
    log_success "Finished"
end

function stow_config
    log_step "Stow config"

    # Configure stow first
    stow --target $HOME --ignore Brewfile stow
    or fail

    for package in */
        stow --target $HOME $package
        or fail
    end
end

function configure_homebrew
    set -gx HOMEBREW_NO_ENV_HINTS 1
    set -gx HOMEBREW_NO_ANALYTICS 1
    set -gx HOMEBREW_NO_INSECURE_REDIRECT 1
end

function update_homebrew
    log_step "Update Homebrew"
    brew update
    or fail
end

function generate_homebrew_bundle
    log_step "Generate Homebrew bundle"
    $HOME/bin/generate-homebrew-bundle
    or fail
end

function install_homebrew_bundle
    log_step "Check Homebrew bundle"
    if not brew bundle check --global --verbose
        log_step "Install Homebrew bundle"
        brew bundle install --global
        or fail
    end
end

function run_install_scripts
    for installer in */install
        log_step "Install "(dirname $installer)
        $installer
        or fail
    end
end

function fail
    log_error "Failed"
    exit 1
end

function log_step
    echo -e "\033[1m──→ $argv[1]\033[0m"
end

function log_success
    echo -e "\033[1;32m──→ $argv[1]\033[0m"
end

function log_error
    echo -e "\033[1;31m──X $argv[1]\033[0m"
end

cd $HOME/.dotfiles/
main
