# Don't print a new line at the start of the prompt
add_newline = false

# Don't print a new line after the prompt - for compatability with Warp terminal
[line_break]
disabled = true

[aws]
disabled = true

[[battery.display]]
threshold = 5

[docker_context]
disabled = true

[golang]
disabled = true

[gcloud]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true
