status --is-interactive; and . (rbenv init -|psub)

# Aliases
alias bake='bundle exec rake'
alias be='bundle exec'
alias bi='bundle install'
alias es='exercism submit'
alias ef='exercism fetch'
alias fs='foreman start'
alias irb='irb -r irb/completion'
alias j='jekyll serve'
alias ll='ls -alG'
alias ls='ls -G'
alias o='open .'
alias r='rspec'
alias rs='rspec spec'
alias rt='rake test'
alias s='subl .'
alias sbp='subl ~/.bash_profile'
alias sgc='subl ~/.gitconfig'
alias t='gittower .'
